/* eslint-disable no-shadow */
export enum ErrorCodes {
  GENERAL = 'GENERAL_ERROR',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  RESPONSE_ERROR = 'RESPONSE_ERROR',
  TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND',
  RECORD_NOT_FOUND = 'RECORD_NOT_FOUND',
  WRONG_CREDENTIALS = 'WRONG_CREDENTIALS',
  UN_SETTED_VARIABLE = 'UN_SETTED_VARIABLE',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  CREDENTIALS_REQUIRED = 'CREDENTIALS_REQUIRED',
  SQL_VALIDATION_ERROR = 'SQL_VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NO_REFERENCED_FOREIGN_KEY = 'NO_REFERENCED_FOREIGN_KEY',
  }

export enum TypeErrors {
    TECNICO = 'TECNICO',
    NOTFOUND = 'NOT FOUND',
    ECONNRESET = 'ECONNRESET',
    BAD_REQUEST = 'BAD REQUEST',
    ECONNREFUSED = 'ECONNREFUSED',
    ECONNABORTED = 'ECONNABORTED',
    INVALID_VALUES = 'INVALID VALUES',
    INTERNAL_ERROR = 'INTERNAL ERROR',
    UNAUTHORIZED = 'AUTHENTICATION ERROR'
  }

export enum ResponseStstus {
    SUCCESS = 200,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    INTERNAL_ERROR = 500
  }
